import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/auth'
import { google } from 'googleapis'
import type { slides_v1 } from 'googleapis'
import { validateDeck } from '@/lib/validator'
import type { SlidePlan } from '@/lib/types'

// Re-runs the SAME checks validateDeck applies at generation time (max_chars,
// bento_layout, bounds, etc.) against an ALREADY-EXISTING deck — the plan is
// reconstructed from each slide's ##SLOTS## speaker-notes payload (written at
// generation time, see lib/google.ts), so nothing needs to be re-supplied.
// Used by scripts/check-deck.ts to diff two generations without a human
// copy-pasting the /result page's validator panel by hand.

function getOAuth2Client(accessToken: string) {
  const oauth2 = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET,
  )
  oauth2.setCredentials({ access_token: accessToken })
  return oauth2
}

function getSlideNotes(slide: slides_v1.Schema$Page): string {
  return (slide.slideProperties?.notesPage?.pageElements ?? [])
    .map(el => (el.shape?.text?.textElements ?? []).map(te => te.textRun?.content ?? '').join(''))
    .join('')
}

function parseSlotPlan(notes: string): { composition: string; slots: Record<string, string> } | null {
  const marker = '##SLOTS##\n'
  const idx = notes.indexOf(marker)
  if (idx < 0) return null
  const jsonStart = idx + marker.length
  const jsonEnd = notes.indexOf('\n', jsonStart)
  const raw = jsonEnd >= 0 ? notes.slice(jsonStart, jsonEnd) : notes.slice(jsonStart)
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}

export async function GET(request: NextRequest) {
  const session = await auth()
  if (!session?.accessToken) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { searchParams } = new URL(request.url)
  const presentationId = searchParams.get('id')
  if (!presentationId) {
    return NextResponse.json({ error: 'Missing ?id=<presentationId> query param' }, { status: 400 })
  }

  const auth2 = getOAuth2Client(session.accessToken)
  const slidesApi = google.slides({ version: 'v1', auth: auth2 })

  const pres = await slidesApi.presentations.get({ presentationId })
  const slidesData = pres.data.slides ?? []

  const planSlides: SlidePlan['slides'] = []
  const planPageIds: string[] = []
  const skipped: number[] = []

  slidesData.forEach((slide, i) => {
    const parsed = parseSlotPlan(getSlideNotes(slide))
    if (!parsed || !slide.objectId) {
      skipped.push(i)
      return
    }
    planSlides.push({ id: slide.objectId, composition: parsed.composition, slots: parsed.slots, flags: {} })
    planPageIds.push(slide.objectId)
  })

  if (planSlides.length === 0) {
    return NextResponse.json(
      { error: 'No slide carries a ##SLOTS## notes payload — was this deck generated by this tool?' },
      { status: 400 },
    )
  }

  const plan: SlidePlan = { theme: 'dark', slides: planSlides }
  const validation = await validateDeck(slidesApi, presentationId, plan, planPageIds)

  return NextResponse.json({
    presentationId,
    title: pres.data.title ?? '',
    skippedSlides: skipped,
    validation,
  })
}
